#create_clock -period 6.515 -name fpga_clkoutp -waveform {0.000 3.257} [get_ports fpga_clkoutp]
#create_clock -period 5.000 -name sysclkp -waveform {0.000 2.500} [get_ports sysclkp]
create_clock -period 6.510 -name cdcoutp -waveform {0.000 3.255} [get_ports cdcoutp]
set_property PACKAGE_PIN L25 [get_ports cdcoutp]
#set_property IOSTANDARD LVDS [get_ports sysclkp]
#set_property IOSTANDARD LVDS [get_ports sysclkn]
set_property IOSTANDARD LVDS_25 [get_ports cdcoutp]
set_property IOSTANDARD LVDS_25 [get_ports cdcoutn]
set_property IOSTANDARD LVDS_25 [get_ports dac_framep]
set_property PACKAGE_PIN AB7 [get_ports reset]
set_property IOSTANDARD LVCMOS15 [get_ports reset]
#set_property PACKAGE_PIN AF22 [get_ports fpga_clkoutp]
set_property PACKAGE_PIN AG30 [get_ports dac_framep]
#set_property IOSTANDARD LVDS_25 [get_ports fpga_clkoutp]
#set_property IOSTANDARD LVDS_25 [get_ports fpga_clkoutn]
set_property IOSTANDARD LVDS_25 [get_ports dac_dataclkp]
set_property PACKAGE_PIN AC29 [get_ports {dac_datap[0]}]
set_property PACKAGE_PIN AD29 [get_ports {dac_datap[1]}]
set_property PACKAGE_PIN AE28 [get_ports {dac_datap[2]}]
set_property PACKAGE_PIN AC26 [get_ports {dac_datap[3]}]
set_property PACKAGE_PIN AJ27 [get_ports {dac_datap[4]}]
set_property PACKAGE_PIN AF26 [get_ports {dac_datap[5]}]
set_property PACKAGE_PIN AC22 [get_ports {dac_datap[6]}]
set_property PACKAGE_PIN AA20 [get_ports {dac_datap[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_datap[0]}]
set_property PACKAGE_PIN AG27 [get_ports dac_dataclkp]


set_property PACKAGE_PIN F16 [get_ports {led[7]}]
set_property PACKAGE_PIN E18 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[6]}]
set_property PACKAGE_PIN G19 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[5]}]
set_property PACKAGE_PIN AE26 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[3]}]
set_property PACKAGE_PIN AB9 [get_ports {led[3]}]
set_property PACKAGE_PIN AC9 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[2]}]
set_property PACKAGE_PIN AA8 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[1]}]
set_property PACKAGE_PIN AB8 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS15 [get_ports {led[0]}]

#set_property PACKAGE_PIN L25 [get_ports cdcoutp]

#set_property PACKAGE_PIN AD12 [get_ports sysclkp]

